import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home()
{
  return (
      <div className={styles.container}>

      <Head>
        <title>EventWave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <h1>Hey This Is Instagram 2.0</h1>

          {/*header*/}


    </div>
  )
}
